name: notify
on:
  workflow_run:
    workflows: [push-page-to-prod]
    types: [completed]
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - run: echo 'The triggering workflow passed'
      - run: pip install requests
      - run: python notify.py green ${{ secrets.LIFX_TOKEN }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - run: echo 'The triggering workflow failed'
      - run: pip install requests
      - run: python notify.py red ${{ secrets.LIFX_TOKEN }}